### ISSUE TITLE
Re-activating revision

### ISSUE THREAD

**Issue by horihiro** [Azure/aca-review-apps#46]
If a revision is deactivated by closing PR or something, there is no feature to re-activate the revision by this action in case of re-opening the PR.
Do we need to provide a way for re-activation by this action?

**Comment by yuhattor** [comment]
In the first place, it is not possible to reopen a PR that has been merged.
In addition, a new PR could be opened for a new review, so that it can be addressed. In many cases, they will link past PRs within that PR.
There will be very few cases where there is no other option but to reopen a past Pull Request.
So I don't think Reactivate is necessary.
