### ISSUE TITLE
Repository should contain compiled lib/main.js

### ISSUE THREAD

**Issue by georgeOsdDev** [Azure/aca-review-apps#48]
Currently this repository does not contain `lib/main.js`. This cause below error.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/1381907/191245531-159b3a13-7090-46d6-a6b1-4a3be20c9d88.png">

See below instruction
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Comment by yuhattor** [comment]
Thanks for your input:) 

Indeed, we are considering adding lib/main.js before releasing it to the marketplace. However, how to manage all the artifact files is still under consideration. We need all node_modules as well as lib.js for the release. Since we are developing in typescript, we need to build every time the main branch is updated.

This action is in reference to the [App Service Action](https://github.com/Azure/webapps-deploy) and [ACI Deployment Action](https://github.com/azure/aci-deploy), but it appears that at least the main branch is not updated every time, and a stable version is placed there. On the contrary, lib/main.js has not even been updated for a long time, even though there are changes in src.

Since most GitHub Actions are not frequently updated once released, it would seem that the only operation is to set a release tag. At the very least, there should be documentation on how to test this and how to check it at hand. Or, we need to provide a way to make testing easier without updating the main branch.

**Comment by yuhattor** [comment]
@georgeOsdDev We added initial release, if possible, could you try it out?
https://github.com/Azure/aca-review-apps/releases/tag/v0.1.0

**Comment by yuhattor** [comment]
We released the initial developer preview, so we close the issue:)
Thank you for your comment!
